![Logo ITQ](./img/logoitqv1.jpg)

Sexto Programa en Python

# Python 1, NumPy

![Logo Python](./img/python_logo.png)

* Nombre: *Christian Zumárraga*
* Fecha : **7-07-2026**
* Repositorio: *[Link del repositorio de GitHub](https://github.com/Crishito/machine12026/blob/main/practicas/Python_Numpy.ipynb)*

# NumPy ndarray

* NumPy (**Num** erical **Py** thon) es la de facto librería estándar para análisis numérico en Python
* Estructura de datos multidimensional eficiente (escrita en C): ndarray
* Colección de funciones para álgebra lineal, estadística descriptiva
* Ayuda al procesamiento de datos (np.where)


In [1]:
#importar libreria
import numpy as np

## Performance Sample, NumPy vs Plain Python

In [2]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 766 ms
Wall time: 828 ms


In [3]:
my_arr = np.arange(10000000) # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 36.3 ms


## Formas de crear ndarrays

In [4]:
# Crear un arreglo bidimensional (2D) con NumPy
array = np.array([[2, 71, 0, 34], [2, 171, -35, 34]])

# Mostrar el contenido del arreglo
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [5]:
# Crear una lista bidimensional (2D) de compras
shopping_list = [['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes']] # 2D

# Convertir la lista en un arreglo (ndarray) de NumPy
array = np.array(shopping_list)

# Mostrar el arreglo
print(array)

# Mostrar el tipo de dato del arreglo
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [6]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1)) # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [7]:
# Generar arrays con valores fijos
print(np.zeros(2)) # 1D
print(np.ones((4,3))) # matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(3)) # matrix identity

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Obtener información sobre ndarray

In [8]:
# Crear un arreglo unidimensional (1D) con NumPy
my_ndarray = np.array([2, 71, 0, 34])

# Mostrar el contenido del arreglo
print(my_ndarray)

[ 2 71  0 34]


In [9]:
print(my_ndarray.argmax()) # índice del valor más alto
print(np.amax(my_ndarray))

print(my_ndarray.argmin()) # índice del valor más bajo
print(np.amin(my_ndarray))

print(my_ndarray.nonzero()) # retorna los índices de los elementos distintos a 0

1
71
2
0
(array([0, 1, 3]),)


In [10]:
my_ndarray = np.full((5, 4,2), 2) # matrix 5x2x2
print(my_ndarray)

print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
40
(5, 4, 2)
3


In [11]:
my_ndarray = np.array([2,71,0,34])

print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

4
(4,)
1


**Redimensionar los datos**

In [12]:
 # matrix 1x8
# Crear una matriz de 1 fila y 8 columnas
my_ndarray = np.array([[0, 71, 21, 19, 213, 412, 111, 98]])

# Mostrar la matriz
print(my_ndarray)

# Mostrar sus dimensiones (filas y columnas)
print(my_ndarray.shape)

# Mostrar el número de dimensiones
print(my_ndarray.ndim)

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [13]:
# Cambiar la forma de la matriz a 2 filas y 4 columnas
new_dims = my_ndarray.reshape(2, 4) # cambiar las dimensiones a 2x4

# Mostrar la nueva matriz
print(new_dims)

# Mostrar el número de dimensiones
print(new_dims.ndim)

[[  0  71  21  19]
 [213 412 111  98]]
2


In [14]:
# Cambiar la forma de la matriz a 4 filas y 2 columnas
new_dims = my_ndarray.reshape(4, 2) # cambiar las dimensiones a 4x2

# Mostrar la nueva matriz
print(new_dims)

# Mostrar el número de dimensiones
print(new_dims.ndim)

[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [15]:
# Crear un arreglo y convertirlo en una matriz de 3 filas y 1 columna
x = np.array([100, 10, 1]).reshape(3, 1)

# Mostrar el tamaño de la matriz
print(x.shape)

# Mostrar la matriz
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [16]:
# reducir a 1D
# Crear una matriz de 3 filas y 3 columnas
new_dims = np.arange(9).reshape(3, 3)

# Mostrar la matriz
print(new_dims)

# Convertir la matriz en un arreglo de una dimensión (1D)
print(new_dims.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [17]:
# reducir
# Crear una matriz de 4 filas y 4 columnas
new_dims = np.arange(16).reshape(4, 4)

# Mostrar la matriz
print(new_dims)

# Reorganizar la matriz en 2 filas; las columnas se calculan automáticamente
print(new_dims.reshape(2, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## Manipulación de ndarrays

In [18]:
# Cambiar ejes
# Crear una matriz de 8 filas y 2 columnas
new_dims = np.arange(16).reshape(8, 2)

# Mostrar la matriz
print(new_dims)

# Intercambiar las filas por las columnas
print(new_dims.swapaxes(0, 1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [19]:
# Flip
# Crear una matriz de 4 filas y 4 columnas
new_dims = np.arange(16).reshape(4, 4)

# Mostrar la matriz
print(new_dims)

# Invertir el orden de todos los elementos de la matriz
print(np.flip(new_dims, axis=None))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [20]:
# ordenar
# Crear un arreglo con números desordenados
array1 = np.array([10, 2, 9, 17])

# Ordenar los elementos de menor a mayor
array1.sort()

# Mostrar el arreglo ordenado
print(array1)

[ 2  9 10 17]


In [21]:
# Juntar dos arrays
# Crear dos arreglos con seis elementos cada uno
a1 = [0, 0, 0, 0, 0, 0]
a2 = [1, 1, 1, 1, 1, 1]

# Unir los arreglos horizontalmente (uno al lado del otro)
print(np.hstack((a1, a2)))
print(np.hstack((a1, a2)).shape)

# Unir los arreglos verticalmente (uno encima del otro)
print(np.vstack((a1, a2)))
print(np.vstack((a1, a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [22]:
# Crear dos matrices de 2 filas y 2 columnas
array1 = np.array([[2, 4], [6, 8]])
array2 = np.array([[3, 5], [7, 9]])

# Unir las matrices por filas (eje 0)
print(np.concatenate((array1, array2), axis=0))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [23]:
 # dividir un array
# Crear una matriz de 4 filas y 4 columnas
array = np.arange(16).reshape(4, 4)

# Mostrar la matriz
print(array)

# Dividir la matriz en 2 partes iguales por filas
print(np.array_split(array, 2, axis=0))

# Dividir la matriz en 3 partes
print(np.array_split(array, 3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [24]:
# Crear una matriz de 4 filas y 4 columnas
array = np.arange(16).reshape(4, 4)

# Mostrar la matriz
print(array)

# Dividir la matriz por la columna de índice 3
print(np.array_split(array, [3], axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [25]:
# Dividir la matriz por la columna de índice 3
split = np.array_split(array, [3], axis=1)

# Mostrar el elemento de la fila 4 y columna 1 de la primera matriz
print(split[0][3][0])

12


In [26]:
# Crear una matriz de 8 filas y 8 columnas
array = np.arange(64).reshape(8, 8)

# Mostrar la matriz
print(array)

# Dividir la matriz por las filas de índice 1 y 3
print(np.array_split(array, [1, 3], axis=0))

# Dividir la matriz por las columnas de índice 1 y 3
print(np.array_split(array, [1, 3], axis=1))

# axis = n_dimensions - 1
# axis = 0 → filas
# axis = 1 → columnas

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

# Índices y slicing

* De manera análoga a índices y slicing para listas

In [27]:
# Crear un arreglo con valores del 10 al 15
array = np.arange(10, 16)

# Mostrar el arreglo
print(array)

# Mostrar el último elemento del arreglo
print(array[-1]) # acceso unidimensional

# Mostrar todos los elementos excepto el último
print(array[:-1]) # slice

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [28]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna
print(array[3][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [29]:
# Crear un arreglo de 3 dimensiones (2 × 3 × 6)
array = np.arange(36).reshape(2, 3, 6)

# Mostrar el arreglo
print(array)

# Acceder a un elemento usando una sola indexación
print(array[0, 2, 4])

# Acceder al mismo elemento usando indexación por niveles
print(array[1][2][4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


**NumPy es row major**

In [30]:
# Crear un arreglo con 6 elementos
row_major = np.array([1, 2, 3, 4, 5, 6])

# Convertir el arreglo en una matriz de 2 filas y 3 columnas
row_major = row_major.reshape(2, 3) # by default, row major

# Mostrar la matriz
print(row_major)

[[1 2 3]
 [4 5 6]]


In [31]:
# Crear un arreglo y organizarlo por filas (orden C)
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2, 3, order='C') # by default, row major
print(row_major)

# Crear un arreglo y organizarlo por columnas (orden F)
col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2, 3, order='F') # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


**Slice**

In [32]:
# se puede hacer slice por fila o columna
# Crear una matriz de 9 filas y 9 columnas
array = np.arange(81).reshape(9, 9)

# Mostrar la matriz
print(array)

# Seleccionar las filas 1 y 2, y las columnas desde la 2 hasta el final de dos en dos
print(array[1:3, 2::2])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [33]:
# se puede hacer slice por fila o columna
# Crear una matriz de 3 filas y 3 columnas
array = np.arange(9).reshape(3, 3)

# Mostrar la matriz
print(array)

# Mostrar la primera fila de la matriz
print(array[0, :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


**Diferencias entre índices y slicing en listas y ndarrays:**

* ¡Retornan una referencia, no una copia!

In [34]:
# uso de slice en listas, retorna copia
# Crear una lista con valores del 0 al 9
lista = [0,1,2,3,4,5,6,7,8,9]

# Crear una copia de los dos primeros elementos
my_copy = lista[0:2] # devuelve una copia

# Mostrar la copia
print(my_copy)

# Modificar el primer elemento de la copia
my_copy[0] = 222

# Mostrar la lista original y la copia modificada
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [35]:
# slicing retorna una referencia en ndarrays
# Crear un arreglo con valores del 0 al 9
array = np.arange(10)

# Obtener una referencia a una parte del arreglo
my_copy = array[2:5] # devuelve una referencia

# Mostrar el arreglo original y la referencia
print(array)
print(my_copy)

# Modificar el primer elemento de la referencia
my_copy[0] = 222

# Mostrar el arreglo original y la referencia después del cambio
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [36]:
# copiar ndarrays
# Crear un arreglo con valores del 0 al 9
array = np.arange(10)

# Crear una copia independiente de una parte del arreglo
my_copy = array[2:5].copy() # hay que hacer la copia explicitamente

# Modificar el primer elemento de la copia
my_copy[0] = 222

# Mostrar el arreglo original y la copia
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


* Permite asignar valores a un corte

In [37]:
# Crear un arreglo con valores del 0 al 9
array = np.arange(10)

# Mostrar el arreglo y los tres primeros elementos
print(array)
print(array[0:3])

# Reemplazar los tres primeros elementos por -1
array[0:3] = -1

# Mostrar el arreglo modificado
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


* Slicing condicionales (mask)

In [38]:
# slicing condicional
# Crear un arreglo con valores del -3 al 3
array = np.arange(-3, 4)

# Mostrar el arreglo
print(array)

# Crear una máscara con los números pares
mask = array % 2 == 0
print(mask)

# Mostrar los elementos que cumplen la condición
print(array[mask])
print(array[array % 2 == 0])

# Reemplazar los números pares por 0
array[mask] = 0

# Mostrar el arreglo modificado
print(array)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [39]:
# Crear un arreglo con valores del -3 al 3
array = np.arange(-3, 4)

# Mostrar el arreglo
print(array)

# Reemplazar los valores negativos por 0
array[array < 0] = 0

# Mostrar el arreglo modificado
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [40]:
# slicing condicional
# Crear un arreglo con valores del -3 al 3
array = np.arange(-3, 4)

# Mostrar el arreglo
print(array)

# Crear una máscara con los números pares
mask = array % 2 == 0
print(mask)

# Obtener una copia de los números pares
array_par = array[mask] # devuelve una copia
print(array_par)

# Modificar el primer elemento de la copia
array_par[0] = -10

# Mostrar el arreglo original y la copia modificada
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


* Acceso a múltiples valores con listados de índices

In [41]:
import numpy as np

array = np.arange(0,16).reshape(4,4) # Matriz 4x4 (0 al 15)
print(array)

print(array[[1,2]]) #selecting rows
print(array[:,[1,2]]) #selecting columns

# cross product of indexes
print(array[[1,2],:][:,[1,2]])
print(array[np.ix_([1,2],[1,2])]) # built in ix_ (Cruce optimizado)

ar = array[[2,3,1]] # slice, copia (independiente en memoria)
print(ar)

ar[0] = 999 # Se muta únicamente la copia
print(ar)

print(array) # Se comprueba que la matriz original sigue intacta

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[999 999 999 999]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Funciones matemáticas

* Aplicar operaciones entre escalares y arrays o entre arrays

In [42]:
# listas y escalares
lista = [0,1,2,3] # Se crea la colección inicial
lista *= 3 # Repite los elementos de la lista 3 veces (modifica la lista original)
print(lista) 

lista += [1] # Concatena (agrega) una nueva lista con el valor 1 al final
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [43]:
import numpy as np

# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int8) # Crea arreglo de cuatro 1s (tipo entero de 8 bits)
print(array)

array *= 2 # Multiplica todos los elementos por 2 simultáneamente
print(array)

array += 10 # Suma 10 a todos los elementos simultáneamente
print(array)
print(array.dtype) # check data type of array

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [44]:
import numpy as np

# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2 # Crea arreglo de cuatro 2s: [2., 2., 2., 2.]
array_2 = np.arange(4) + 1 # Crea arreglo del 1 al 4: [1, 2, 3, 4]

print(array_1)
print(array_2)

# Las operaciones aritméticas se aplican posición por posición (elemento a elemento)
print(array_1 + array_2) # Suma
print(array_1 - array_2) # Resta
print(array_1 * array_2) # Multiplicación
print(array_2 / array_1) # División

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


## Broadcasting

Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande -> [broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

## Operadores unarios y binarios

| Tipo | Operación | Descripción |
| :--- | :--- | :--- |
| **Unario** | *`abs`* | Valor absoluto de cada elemento |
| | *`sqrt`* | Raíz cuadrada de cada elemento |
| | *`exp`* | e^x, siendo x cada elemento |
| | *`log`, `log10`, `log2`* | Logaritmos en distintas bases de cada elemento |
| | *`sign`* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *`ceil`* | Redondea cada elemento por arriba |
| | *`floor`* | Redondea cada elemento por abajo |
| | *`isnan`* | Retorna si cada elemento es Nan |
| | *`cos`, `sin`, `tan`* | Operaciones trigonométricas en cada elemento |
| | *`arccos`, `arcsin`, `arctan`* | Inversas de operaciones trigonométricas en cada elemento |
| **Binario** | *`add`* | Suma de dos arrays |
| | *`subtract`* | Resta de dos arrays |
| | *`multiply`* | Multiplicación de dos arrays |
| | *`divide`* | División de dos arrays |
| | *`maximum`, `minimum`* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *`equal`, `not_equal`* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *`greater`, `greater_equal`, `less`, `less_equal`* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [45]:
import numpy as np

# ejemplos de operadores
array = np.arange(5) # Crea un arreglo del 0 al 4
print(array)

np.sqrt(array) # Operador unario: calcula la raíz cuadrada elemento a elemento

[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [46]:
import numpy as np

# ejemplos de operadores
array1 = np.arange(4) # Crea un arreglo: [0, 1, 2, 3]
array2 = np.array([0, -1, 2, -3]) # Crea un arreglo manual

print(array1)
print(array2)

# Comparaciones lógicas elemento a elemento
print(np.greater(array1, array2)) # Operador binario: ¿array1 es mayor que array2? 
print(np.less(array2, array1)) # Operador binario: ¿array2 es menor que array1?

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


# Estadística descriptiva

* Importante saber la naturaleza de los datos
* Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
| :--- | :--- |
| *`sum(arr)`* | Suma de todos los elementos de *arr* |
| *`mean(arr)`* | Media aritmética de los elementos de *arr* |
| *`std(arr)`* | Desviación estándar de los elementos de *arr* |
| *`cumsum(arr)`* | Devuelve array con la suma acumulada de cada elemento con todos los anteriores |
| *`cumprod(arr)`* | Devuelve array con el producto acumulado de cada elemento con todos los anteriores |
| *`min(arr), max(arr)`* | Mínimo y máximo de *arr* |
| *`any(arr)`* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *`all(arr)`* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o <>0 en valores numéricos) |
| *`unique(arr)`* | Devuelve un array con valores únicos |
| *`in1d(arr1, arr2)`* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *`union1d(arr1, arr2)`* | Devuelve la unión de ambos arrays |
| *`intersect1d(arr1, arr2)`* | Devuelve la intersección de ambos arrays |

In [47]:
import numpy as np

# sum != cumsum
array1 = np.arange(9) # Crea un arreglo del 0 al 8: [0, 1, 2, 3, 4, 5, 6, 7, 8]
print(array1)

print(array1.sum()) # Calcula la suma total de todos los elementos
print(array1.cumsum()) # Calcula la suma acumulada posición por posición

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [48]:
import numpy as np

# any vs all
array1 = np.arange(-8, 2).reshape(2, 5) # Crea matriz 2x5 con valores del -8 al 1
print(array1)

print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores <> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [49]:
import numpy as np

# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5) # Crea matriz 2x5 con valores del 0 al 9
print(array1)

print(array1.all(axis=0)) # Evalúa la condición columna por columna (Vertical)
print(array1.all(axis=1)) # Evalúa la condición fila por fila (Horizontal)
print(array1.all()) # Evalúa toda la matriz de forma global

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


# 5 Álgebra lineal

* `numpy.linalg` contiene funciones para álgebra lineal
* dot product, multiplicación de matrices, cálculo del determinante, factorizaciones...

| Función | Descripción |
| :--- | :--- |
| *`dot(mat1, mat2)`* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *`matmul(mat1, mat2)`* | Devuelve el producto entre dos matrices |
| *`trace(mat, mat2)`* | Suma de las diagonales de la matriz |
| *`det(mat)`* | Devuelve el determinante de la matriz |
| *`eig(mat)`* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *`inv(mat)`* | Devuelve la inversa de la matriz |
| *`qr(mat)`* | Computa la factorización QR de *mat* |
| *`solve(A, b)`* | Resuelve el sistema lineal de ecuaciones *Ax = b para b,* cuando *A* es una matriz cuadrada |
| *`transpose(mat)`* | Devuelve la transpuesta de la matriz |

In [50]:
import numpy as np

A = np.arange(12).reshape(4,3) # Crea matriz de 4 filas por 3 columnas
B = np.arange(6).reshape(3,2) # Crea matriz de 3 filas por 2 columnas

print(A)
print(B)

# Multiplicación de matrices (Álgebra Lineal)
print(np.matmul(A, B)) # Método 1: Función explícita de NumPy para producto de matrices
print(np.dot(A, B)) # Método 2: Producto escalar (en 2D es equivalente a la multiplicación de matrices)
print(A @ B) # Método 3: Operador nativo de Python para multiplicación de matrices

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [51]:
import numpy as np # Aseguramos la importación principal
import numpy.linalg as lg
import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x

# 11 (Omitido para evitar error de sintaxis)

a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ]) # Matriz 'A' con los coeficientes de las variables
b = np.array([12,2,32]) # Vector 'b' con los términos independientes (resultados)

print(a)
print(b)

x,y,z = lg.solve(a,b) # Resuelve automáticamente el sistema de ecuaciones
print(f'x={x} y={y} z={z}')

# Comprobación: Se reemplazan las variables halladas en las ecuaciones originales
# math.isclose() verifica que el resultado sea correcto, ignorando minúsculos errores de precisión de decimales (flotantes)
print(math.isclose(3*x + 2*y +5*z, 12)) 
print(math.isclose(x - 3*y - z, 2))
print(math.isclose(2*x -y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122808 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [52]:
import numpy as np

# matriz identidad
I = np.identity(4) # Crea una matriz identidad de 4x4 (unos en la diagonal principal, ceros en el resto)
print(I)

A = np.arange(16).reshape(4,4) # Crea una matriz de 4x4 con valores del 0 al 15
print(A)

print(np.matmul(A, I)) # Multiplica la matriz A por la matriz identidad I

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


# Filtrado de datos

* Filtrar y modificar datos numéricos con np.where
* Retorna A o B en función de una condición en una array

In [53]:
import numpy as np

prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49]) # Crea el arreglo original
mask = prices < 1 # Genera una máscara booleana (True donde sea menor a 1)

print(prices[prices < 1]) #slicing condicional -> Filtra y muestra solo los valores que cumplen la condición

# mask con los elementos menores de 1
# mask = np.where(prices < 1, True, False)
# print(mask)
# print(prices[mask])

# prices[mask] = 1.0
# print(prices)

# np.where(condición, valor_si_cumple, valor_si_no_cumple)
print(np.where(prices < 1, 1.0, prices)) # Evalúa y reemplaza dinámicamente los menores a 1 por 1.0

[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]


In [54]:
import numpy as np

# Se puede usar para sustituir datos fuera de rango
# Crea matriz 2x3 con valores positivos y negativos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3) 
print(bank_transfers_values)

# np.where(condición, valor_si_cumple, valor_si_no_cumple)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0) # Reemplaza anomalías por 0
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [55]:
import numpy as np

# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3] # np.nan --> NotANumber, elemento especial (lista original)
data_clean = np.where(np.isnan(data), 0, data) # Detecta el NaN y lo reemplaza por 0 dinámicamente

print(data_clean) # Salida con el dato ya imputado

print(id(data)) # Muestra la dirección en memoria de la lista original
print(id(data_clean)) # Muestra la dirección en memoria del nuevo arreglo (son diferentes)

[  10.   12. -143.    0.    1.   -3.]
1591715007488
1593128779472


In [56]:
import numpy as np

# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3) # Crea la matriz 2x3
print(bank_transfers_values)

# Si usas np.where() solo con la condición, no reemplaza, sino que extrae coordenadas
credits = np.where(bank_transfers_values > 0) # array de índices para los que la condición es True
print(credits) # Muestra una tupla de arreglos con los índices (filas y columnas) exactos

# Usa las coordenadas extraídas para filtrar la matriz original
print(bank_transfers_values[credits]) # es igual que bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0]) # Mismo resultado, pero usando slicing condicional directo

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [57]:
import numpy as np

# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6) # Recompensas normales
print(rewards_default)

rewards_upgrade = np.arange(6) * 10 # Recompensas mejoradas
print(rewards_upgrade)

daily_points = np.array([0, 0, 1, 6, 0, 2]) # Puntos obtenidos (arreglo de evaluación)
print(daily_points)

# np.where(condición, array_si_cumple, array_si_no_cumple)
final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default) 
print(final_rewards) # Salida

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


# Números aleatorios

* Python módulo random

In [58]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores

0.3058180375956925
4
2.144858035146378


In [59]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)

'Pikachu'

## NumPy.random

* Generar fácilmente listas con valores aleatorios

In [60]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.9649553117142587
4
[[0 1 0 4]
 [3 4 1 0]]


In [61]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[-0.7252357   0.20729951]
 [ 2.05114542 -0.16092282]
 [ 0.04835544 -0.51406597]
 [-0.5717637   1.86405784]]


In [62]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias esperadas, retornar 'size' valores

0
4.5005229890006575
[[0 1]
 [0 0]]


## Random seed

* Números pseudo-aleatorios
* Ordenadores generan números a partir de ecuaciones
* Basadas en un número inicial (seed)
* Bueno para reproducibilidad de experimentos

In [63]:
import numpy as np

i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla -> Al fijar la semilla en 5 al inicio de cada iteración, el generador se reinicia
    print(np.random.rand()) # Imprimirá exactamente el mismo primer número las 5 veces
    print(np.random.rand()) # Imprimirá exactamente el mismo segundo número las 5 veces
    print()

for i in range(6):
    np.random.seed(i) # diferentes semillas -> La semilla cambia (del 0 al 5) en cada iteración
    print(np.random.rand()) # Genera números pseudoaleatorios diferentes porque el punto de partida cambió
    print(np.random.rand())

0.22199317108973948
0.8707323061773764

0.22199317108973948
0.8707323061773764

0.22199317108973948
0.8707323061773764

0.22199317108973948
0.8707323061773764

0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764


## Escritura y lectura de ndarrays a archivos

* Para futuro acceso
* Compartir datos con otros
* Formato *.npy


In [64]:
import numpy as np
import os

# escribir a archivo
# Crea una ruta segura al archivo dentro de una carpeta llamada 'res'
ruta = os.path.join("res" ,"o_values_array.npy") 

values = np.random.randint(9, size=(3,3)) # Genera matriz 3x3 con enteros aleatorios del 0 al 8
np.save(ruta, values) # Guarda la matriz en el disco duro en formato binario nativo de NumPy (.npy)
print(values) # Muestra la matriz que acaba de ser guardada

[[6 6 0]
 [8 4 7]
 [0 0 7]]


In [65]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[6 6 0]
 [8 4 7]
 [0 0 7]]


In [66]:
import numpy as np
import os

# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")

values1 = np.random.randint(9, size=(3,3))
values2 = np.random.randint(4, size=(2,2))
values3 = np.random.randint(16, size=(4,4))

# np.savez() permite empaquetar varios arreglos en un solo archivo comprimido
# añade la extensión .npz (NumPy Zipped) automáticamente
np.savez(ruta, values1, values2, values3)

In [67]:
import numpy as np
import os

# leer los archivos (retorna un diccionario con las arrays)
# Carga el archivo .npz previamente guardado
npzfile = np.load(os.path.join("res" ,"o_array_group.npz")) 

print(type(npzfile.files)) # Verifica que es una lista de nombres de arreglos
print(npzfile.files) # Imprime las llaves (nombres) almacenadas: ['arr_0', 'arr_1', 'arr_2']

for key in npzfile.files: # array.files contiene el nombre de las arrays (arr_0, arr_1...)
    print(f"\nContenido de {key}:")
    print(npzfile[key]) # Accede al arreglo individual usando su llave

<class 'list'>
['arr_0', 'arr_1', 'arr_2']

Contenido de arr_0:
[[1 5 7]
 [0 1 4]
 [6 2 1]]

Contenido de arr_1:
[[2 3]
 [0 2]]

Contenido de arr_2:
[[ 5 10  0  0]
 [ 4 14  4  9]
 [ 3 11 15  2]
 [ 4  6  9  3]]


### ¿Por qué molestarse con .npy?

* Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
* ¿Para qué escribir los datos de nuevo?

In [68]:
import os
import numpy as np # Importación necesaria

# escribir a archivo
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
    data_str = f.read() # Lee el contenido
    data = data_str.split(',') # Crea lista separando por comas

# Convierte a array 1000x1000 tipo int8
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)

# Guarda en formato binario eficiente .npy
ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)

In [69]:
%%timeit
import os
import numpy as np

# Medición de tiempo de ejecución con la función mágica %%timeit
ruta_csv = os.path.join("res", "fdata.csv")
with open(ruta_csv, 'r') as f:
    data_str = f.read()
    data = data_str.split(',')
    # Conversión directa a ndarray
    data_array = np.array(data, dtype=np.int8).reshape(1000, 1000)

168 ms ± 6.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [70]:
%%timeit
# Medición del tiempo de carga del archivo binario
data = np.load(ruta_npy)

305 μs ± 33.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [71]:
%%timeit
# Benchmarking np.fromfile
data_array = np.fromfile(ruta_csv, dtype=np.int8, sep=",").reshape(1000, 1000)

338 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### velocidad + simplicidad vs memoria

## Ejercicios

* Ejercicios para practicar NumPy: https://github.com/rougier/numpy100/blob/master/100_Numpy_exercises.ipynb

In [72]:
# Ejercicio 1
# Importar el paquete numpy bajo el nombre np
import numpy as np

In [73]:
# Ejercicio 2
# Imprimir la versión de numpy y la configuración
import numpy as np
print(f"Versión: {np.__version__}")
np.show_config()

Versión: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/AdministradorBlue/anaconda3/Library/include
    lib directory: C:/Users/AdministradorBlue/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/AdministradorBlue/anaconda3/Library/include
    lib directory: C:/Users/AdministradorBlue/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    

In [74]:
# Ejercicio 3
# Crear un vector nulo de tamaño 10
import numpy as np
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [75]:
# Ejercicio 4
# Cómo encontrar el tamaño de memoria de cualquier arreglo
import numpy as np
z = np.zeros((10, 10))
print(f"Tamaño en bytes: {z.size * z.itemsize}")

Tamaño en bytes: 800


In [76]:
# Ejercicio 5
# Cómo obtener la documentación de la función add de numpy desde la línea de comandos
import numpy as np
# En Jupyter, puedes usar: np.add?
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [77]:
# Ejercicio 6
# Crear un vector nulo de tamaño 10 pero el quinto valor es 1
import numpy as np
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [78]:
# Ejercicio 7
# Crear un vector con valores que van desde 10 a 49
import numpy as np
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [79]:
# Ejercicio 8: Invertir un vector (el primer elemento se convierte en el último)
import numpy as np
z = np.arange(10)
z = z[::-1]
print(z)

[9 8 7 6 5 4 3 2 1 0]


In [80]:
# Ejercicio 9
# Crear una matriz de 3x3 con valores que van desde 0 a 8
import numpy as np
z = np.arange(9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [81]:
# Ejercicio 10
# Encontrar índices de elementos distintos de cero de [1,2,0,0,4,0]
import numpy as np
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)
